// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransferOrchestration.TransferManagement.Infrastructure.Persistence;

#nullable disable

namespace TransferOrchestration.TransferManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransferManagementDbContext))]
    partial class TransferManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transfer_management")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransferOrchestration.TransferManagement.Application.ProcessManagement.TransferProcessState", b =>
                {
                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("current_step");

                    b.Property<string>("NetworkSubmissionReference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("network_submission_reference");

                    b.Property<string>("NextAction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("next_action");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("TransferId");

                    b.HasIndex("NetworkSubmissionReference")
                        .IsUnique()
                        .HasDatabaseName("ux_transfer_process_states_network_submission_reference")
                        .HasFilter("network_submission_reference IS NOT NULL");

                    b.HasIndex("NextAttemptAtUtc", "TransferId")
                        .HasDatabaseName("ix_transfer_process_states_due_work")
                        .HasFilter("status = 'Active' AND next_action <> 'None' AND next_attempt_at_utc IS NOT NULL");

                    b.ToTable("transfer_process_states", "transfer_management", t =>
                        {
                            t.HasCheckConstraint("ck_transfer_process_states_actionability", "(status = 'Active' AND next_action <> 'None' AND next_attempt_at_utc IS NOT NULL AND current_step IN ('Created', 'ActionScheduled')) OR (status = 'Waiting' AND next_action = 'None' AND next_attempt_at_utc IS NULL AND current_step = 'WaitingForOutcome') OR (status = 'Completed' AND next_action = 'None' AND next_attempt_at_utc IS NULL AND current_step = 'Completed')");

                            t.HasCheckConstraint("ck_transfer_process_states_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_transfer_process_states_correlation_id", "correlation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_transfer_process_states_timestamps", "updated_at_utc >= created_at_utc");
                        });
                });

            modelBuilder.Entity("TransferOrchestration.TransferManagement.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_account_id");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("transfers", "transfer_management");
                });

            modelBuilder.Entity("TransferOrchestration.TransferManagement.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("FirstFailureAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastFailureAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc", "LockedUntilUtc", "Id")
                        .HasDatabaseName("ix_outbox_eligibility");

                    b.ToTable("outbox_messages", "transfer_management", t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempts", "\"Attempts\" >= 0");

                            t.HasCheckConstraint("ck_outbox_dead_letter", "\"Status\" <> 2 OR (\"LockedBy\" IS NULL AND \"LockedUntilUtc\" IS NULL)");

                            t.HasCheckConstraint("ck_outbox_dead_letter_failure", "\"Status\" <> 2 OR \"FirstFailureAtUtc\" IS NOT NULL");

                            t.HasCheckConstraint("ck_outbox_failure_order", "\"FirstFailureAtUtc\" IS NULL OR \"FirstFailureAtUtc\" <= \"LastFailureAtUtc\"");

                            t.HasCheckConstraint("ck_outbox_failure_pair", "(\"FirstFailureAtUtc\" IS NULL) = (\"LastFailureAtUtc\" IS NULL)");

                            t.HasCheckConstraint("ck_outbox_lock", "(\"LockedBy\" IS NULL) = (\"LockedUntilUtc\" IS NULL)");

                            t.HasCheckConstraint("ck_outbox_published", "\"Status\" <> 1 OR \"PublishedAtUtc\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TransferOrchestration.TransferManagement.Infrastructure.Persistence.DailyTransferUsage", b =>
                {
                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("UtcDay")
                        .HasColumnType("date")
                        .HasColumnName("utc_day");

                    b.Property<decimal>("ConsumedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("consumed_amount");

                    b.HasKey("SourceAccountId", "Currency", "UtcDay");

                    b.ToTable("daily_transfer_usages", "transfer_management", t =>
                        {
                            t.HasCheckConstraint("ck_daily_transfer_usage_positive", "consumed_amount > 0");
                        });
                });

            modelBuilder.Entity("TransferOrchestration.TransferManagement.Infrastructure.Persistence.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("ResultOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result_outcome");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_idempotency_records_scope_key");

                    b.ToTable("idempotency_records", "transfer_management", t =>
                        {
                            t.HasCheckConstraint("ck_idempotency_records_completion", "(status = 'Processing' AND completed_at_utc IS NULL) OR (status = 'Completed' AND transfer_id IS NOT NULL AND completed_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TransferOrchestration.TransferManagement.Application.Reconciliation.ReconciliationRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastEnquiryResult")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("last_enquiry_result");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at_utc");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("NetworkSubmissionReference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("network_submission_reference");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TransferId")
                        .IsUnique()
                        .HasDatabaseName("ux_reconciliation_records_transfer_id");

                    b.HasIndex("NextAttemptAtUtc", "Id")
                        .HasDatabaseName("ix_reconciliation_records_due_work")
                        .HasFilter("status = 1 AND next_attempt_at_utc IS NOT NULL");

                    b.ToTable("reconciliation_records", "transfer_management", t =>
                        {
                            t.HasCheckConstraint("ck_reconciliation_records_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_reconciliation_records_status", "(status = 1 AND next_attempt_at_utc IS NOT NULL) OR (status = 2 AND next_attempt_at_utc IS NULL) OR (status = 3 AND next_attempt_at_utc IS NULL)");

                            t.HasCheckConstraint("ck_reconciliation_records_timestamps", "updated_at_utc >= created_at_utc");
                        });
                });

            modelBuilder.Entity("TransferOrchestration.TransferManagement.Application.ProcessManagement.TransferProcessState", b =>
                {
                    b.HasOne("TransferOrchestration.TransferManagement.Domain.Transfers.Transfer", null)
                        .WithOne()
                        .HasForeignKey("TransferOrchestration.TransferManagement.Application.ProcessManagement.TransferProcessState", "TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransferOrchestration.TransferManagement.Application.Reconciliation.ReconciliationRecord", b =>
                {
                    b.HasOne("TransferOrchestration.TransferManagement.Domain.Transfers.Transfer", null)
                        .WithOne()
                        .HasForeignKey("TransferOrchestration.TransferManagement.Application.Reconciliation.ReconciliationRecord", "TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
