// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransferOrchestration.AccountBalance.Infrastructure.Persistence;

#nullable disable

namespace TransferOrchestration.AccountBalance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccountBalanceDbContext))]
    [Migration("20260811100013_InitialAccountBalance")]
    partial class InitialAccountBalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("account_balance")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransferOrchestration.AccountBalance.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("available_balance");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<decimal>("ReservedBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("reserved_balance");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("accounts", "account_balance", t =>
                        {
                            t.HasCheckConstraint("ck_accounts_available_balance_non_negative", "available_balance >= 0");

                            t.HasCheckConstraint("ck_accounts_reserved_balance_non_negative", "reserved_balance >= 0");
                        });
                });

            modelBuilder.Entity("TransferOrchestration.AccountBalance.Domain.Accounts.BalanceReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("FinalisedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalised_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.Property<Guid>("account_id")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.HasKey("Id");

                    b.HasIndex("TransferId")
                        .IsUnique()
                        .HasDatabaseName("ux_balance_reservations_transfer_id");

                    b.HasIndex("account_id");

                    b.ToTable("balance_reservations", "account_balance", t =>
                        {
                            t.HasCheckConstraint("ck_balance_reservations_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("TransferOrchestration.AccountBalance.Domain.Accounts.BalanceReservation", b =>
                {
                    b.HasOne("TransferOrchestration.AccountBalance.Domain.Accounts.Account", null)
                        .WithMany("Reservations")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransferOrchestration.AccountBalance.Domain.Accounts.Account", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
